name: Deploy Gradio App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Deploy to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git config --global user.email = "kealy.slupsky@platotech.com"
        git config --global user.name = "kealys"
        git clone https://kealys:${HF_TOKEN}@huggingface.co/spaces/kealys/test-ci-cd
        cp app.py requirements.txt test-ci-cd/
        cd test-ci-cd
        git add .
        git commit -m "Auto deploy"
        git push https://kealys:${HF_TOKEN}@huggingface.co/spaces/kealys/test-ci-cd
